# FloofOS - Fast Line-rate Offload On Fabric Operating System
# Copyright (C) 2025 FloofOS Networks <dev@floofos.io>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# VPP SNMP Agent Configuration
polling_interval: 30
vpp_socket: /run/vpp/cli.sock
vppcfg_path: /etc/vpp/dataplane.yaml
